drop table processed_data ;

create table processed_data (file_id integer, var_id integer, sample_id integer, 
	latitude real,
	longitude real,
	trap_type text,
	bathy_depth real,
	depth real,
	date_time real,
	date_time_end real,
	duration real,
	area real,
	flux_tot real,
	flux_std_dev real,
	c_flux real,
	c_flux_std_dev real,
	poc_flux real,
	poc_flux_std_dev real,
	pic_flux real,
	pic_flux_std_dev real,
	pon_flux real,
	pon_flux_std_dev real,
	pop_flux real,
	pop_flux_std_dev real,
	psi_flux real,
	psi_flux_std_dev real,
	psio2_flux real,
	psioh4 real,
	pal real,
	pal_std_dev real,
	chl_flux real,
	pheop_flux real,
	caco3_flux real,
	caco3_flux_std_dev real,
	fe_flux real,
	mn_flux real,
	ba_flux real,
	detrital_flux real,
	ti_flux  real,
		CONSTRAINT FK_data_var_id FOREIGN KEY(var_id) REFERENCES variables(var_id) CONSTRAINT FK_data_file_id FOREIGN KEY(file_id) REFERENCES file(file_id));

CREATE INDEX processed_data_file_id_IDX ON "processed_data" (file_id);
CREATE INDEX processed_data_var_id_IDX ON "processed_data" (var_id);
CREATE INDEX processed_data_sample_IDX ON "processed_data" (sample_id);
